apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dead-apricot-vole
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dead-apricot-vole 
  name: dead-apricot-vole
  namespace: rhtap
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dead-apricot-vole
    weight: 100 
