apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dead-apricot-vole
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dead-apricot-vole 
  name: dead-apricot-vole
  namespace: rhtap
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dead-apricot-vole 
